# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jessica Harllee
email: jessica.harllee@gmail.com
url: jessicaharllee.com
timezone: Eastern Time (US & Canada)
description: > # this means to ignore newlines until "baseurl:"
    Jessica Harllee is a product designer at Etsy based out of Brooklyn, NY.
twitter_username: harllee
github_username:  harllee

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock
    - ".gitignore"
    - README*
sass:
    sass_dir: _sass # set the directory for sass files

date_format: "%b %d, %Y"
permalink: pretty

collections:
    uploads:
        title: Uploads
        output: true
    work:
        title: Work
        output: true
    tags:
        title: tags
        output: true
defaults:
- scope:
    path: "" # all files in the project
  values:
    layout: "default" # set the default layout as "default"
- scope:
    path: "" # all files in the project
    type: posts 
  values:
    permalink: "/notes/:title/" # set the path for posts as notes
    layout: post
    tags:
- scope:
    path: ''
    type: tags
  values:
    permalink: "/notes/tags/:title/"
    layout: tags
    alias: 
- scope:
    path: "" # all files in the project
    type: work 
  values:
    layout: post