---
title: jessicaharllee.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
  tags:
    title: tags
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    permalink: "/notes/:title/"
    layout: post
    tags: 
- scope:
    path: ''
    type: tags
  values:
    permalink: "/notes/tags/:title/"
    layout: tags
    alias: 
- scope:
    path: ''
    type: work
  values:
    layout: post
permalink: pretty
