---
title: Jessica Harllee
timezone: Eastern Time (US & Canada)
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
  tags:
    title: tags
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    permalink: "/notes/:title/"
    layout: post
    tags: 
- scope:
    path: ''
    type: tags
  values:
    permalink: "/notes/tags/:title/"
    layout: tags
    alias: 
- scope:
    path: ''
    type: work
  values:
    layout: post
email: jessica.harllee@gmail.com
url: jessicaharllee.com
description: 'Jessica Harllee is a product designer at Etsy based out of Brooklyn,
  NY.

'
twitter_username: harllee
github_username: harllee
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- ".gitignore"
- README*
sass:
  sass_dir: _sass
date_format: "%b %d, %Y"
permalink: pretty
