---
title: Jessica Harllee
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
  tags:
    title: tags
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    permalink: "/notes/:title/"
    layout: post
    tags: 
- scope:
    path: ''
    type: tags
  values:
    permalink: "/notes/tags/:title/"
    layout: tags
    alias: 
- scope:
    path: ''
    type: work
  values:
    layout: post
- scope:
    path: "/recipes/"
  values:
    sitemap: false
url: http://www.jessicaharllee.com
description: Jessica Harllee is a principal product designer in Brooklyn, New York
permalink: pretty
date_format: "%b %d, %Y"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-redirect-from
exclude:
- Gemfile.lock
- node_modules
